list-minor-updates:
  description: Given a package name and a semver version, this program must determine newer minor releases of that package by querying the npm.js registry.
  done: true
  subtasks:
    fetch-list-of-releases-from-npmjs:
      description: Given an existing NPM package name, this program must be able to fetch the list of released versions of that package from npm.js
      done: true

outdatui:
  description: This program must assist with reviewing and installing version updates of outdated NPM dependencies. It must parse the output of `pnpm outdated --format json`. It shows version updates available, fetches release notes, allows to select which releases should be installed, and prints them to stdout when the user confirms their selection.
  done: true
  subtasks:
    render-releases:
      description: The program must render the newer minor releases in a list which allows focusing and selecting releases
      done: true
      subtasks:
        focus:
          description: The user must be able to focus releases with keyboard hotkeys
          done: true
        select:
          description: The user must be able to select entries
          done: true

    confirm-selection:
      description: The user must be able to confirm their selection by pressing Enter. The program should then quit and print the selected releases to stdout.
      done: true

    show-release-notes:
      description: Given a repository URL and a version tag, this program must display the corresponding release notes.
      done: true
      subtasks:
        fetch-release-notes:
          description: Given a GitHub repository URL and a semver version, this program must fetch the release notes of the release with that version from that repository URL.
          done: true
          subtasks:
            fetch-release-notes-from-github:
              description: If the repository is hosted on github.com, try to fetch the release notes of the release with the given semver version. If no release with the given semver version exists, try to fetch the release notes of the release with the given semver version, prefixed with 'v'. If neither a release exists for `<semver>` nor `v<semver>`, return something that indicates that no release notes were found. Otherwise, return the successfully fetched release notes.
              done: true
              subtasks:
                authorize-with-api-token:
                  description: GitHub throttles requests. This app should use a GitHub API token from the environment variables so that GitHub knows who is making the requests and does not throttle them.
                  done: true

            fetch-release-notes-from-non-github:
              description: If the repository is not hosted on github.com, return something that indicates that currently only GitHub is supported
              done: true

    responsivesness:
      description: This program must handle fetching data and receiving keyboard input in parallel, i.e. fetching data should not make the UI unresponsive, nor should keyboard strokes delay fetching data
      done: false

lib:
  description: "This program must curate a library of functionalities shared across binaries"
  done: true
  parse-input:
    description: This program must parse the output of `pnpm outdated --format json`. Behaviour for other input is not defined.
    done: true
    tests:
      parses-successfully:
        arrange: 'Given the string `{ "foo": { "current": "1.0.0", "latest": "1.1.0" }}`'
        assert: The program parses the string successfully and knows that currently, foo@1.0.0 is installed, and foo@1.1.0 is latest
        done: true
  handle-semvers:
    description: This library must be capable of parsing and comparing semvers
    done: true
    tests:
      parsing:
        arrange: Given a semver as a string
        assert: Parses the string to a Semver struct
        done: true
      comparing:
        arrange: Given two Semver struct instances
        assert: Determines which of the one is greater or whether both are equal
        done: true
      filter-minor-versions:
        arrange: Given a list of semvers and a current semver
        assert: The result of this function includes all and only minor version updates for the current version
        done: true
